import type { VfxBriefItem } from "../vfx";

export type ShowcaseScene = {
  section: string;
  subtitle: string;
  effect: VfxBriefItem;
};

const fx = (effect: Partial<VfxBriefItem> & Pick<VfxBriefItem, "id" | "type" | "anchor" | "name" | "duration" | "outputName">): VfxBriefItem => ({
  mode: "自动",
  text: "",
  motion: "",
  sound: "",
  requiredAction: "",
  capcutAction: "",
  ...effect,
});

export const showcaseScenes: ShowcaseScene[] = [
  {
    section: "P2 SHELL",
    subtitle: "先建立统一画面壳：顶部导航、底部进度、场景标签和字幕安全区。",
    effect: fx({
      mode: "自动",
      id: "P2-001",
      type: "ProgramPackage",
      anchor: "你用 AI 生成的 90% 内容，最后都会变成垃圾。",
      name: "视觉系统开场",
      duration: "4秒",
      outputName: "P2-001-ProgramPackage-视觉系统开场.mov",
      eyebrow: "CONTENT OS",
      subLabel: "组件库总览",
      indexText: "01/19",
      titleLines: ["AI内容", "90%变垃圾"],
      highlightLineIndex: 1,
    }),
  },
  {
    section: "P0 EVIDENCE",
    subtitle: "EvidenceCard 展示素材输入：截图、来源、URL、置信度、焦点区域和结论。",
    effect: fx({
      mode: "自动",
      id: "P0-001",
      type: "EvidenceCard",
      anchor: "三个月后，这些东西你还能找到吗？",
      name: "素材证据卡",
      duration: "5秒",
      outputName: "P0-001-EvidenceCard-素材证据卡.mov",
      sourceLabel: "SOURCE_01",
      sourceType: "local_article_render",
      image: "opc-showcase/assets/article-evidence.png",
      title: "内容找不回，就不是资产",
      takeaway: "素材进入视频前，要先证明它能支撑这个判断。",
      confidence: 0.92,
    }),
  },
  {
    section: "P0 EVIDENCE",
    subtitle: "这是外部官网抓取样本：Anthropic 官方 Claude Code 文档，带来源 URL 和置信度。",
    effect: fx({
      mode: "自动",
      id: "P0-001B",
      type: "EvidenceCard",
      anchor: "散在 Claude 的项目对话里。",
      name: "外部官网引用",
      duration: "5秒",
      outputName: "P0-001B-EvidenceCard-外部官网引用.mov",
      sourceLabel: "SOURCE_02",
      sourceType: "official_docs",
      sourceUrl: "https://docs.anthropic.com/en/docs/claude-code/overview",
      image: "opc-showcase/assets/external/anthropic-claude-code.png",
      title: "Claude Code 官方文档",
      takeaway: "公开官方文档适合自动抓取，但仍要记录来源和抓取时间。",
      confidence: 0.91,
    }),
  },
  {
    section: "P0 COMPARE",
    subtitle: "CompareCard 支持文字对比，也支持左右两张素材引用图。",
    effect: fx({
      mode: "自动",
      id: "P0-002",
      type: "CompareCard",
      anchor: "你不是没有产出。你是没有沉淀。",
      name: "产出沉淀对比",
      duration: "4秒",
      outputName: "P0-002-CompareCard-产出沉淀对比.mov",
      eyebrow: "OUTPUT vs ASSET",
      title: "生成内容 vs 沉淀资产",
      leftLabel: "OUTPUT",
      leftText: "聊天记录|桌面文件|最终版文件",
      rightLabel: "ASSET",
      rightText: "选题库|脚本库|复盘库",
      verdict: "真正的差异不是生成速度，而是能不能复用。",
    }),
  },
  {
    section: "P0 COMPARE",
    subtitle: "这是外部截图对比图：Claude Code 官方文档 vs Cursor 官方文档。",
    effect: fx({
      mode: "自动",
      id: "P0-002B",
      type: "CompareCard",
      anchor: "散在 Claude 的项目对话里。散在 Cursor 的临时修改里。",
      name: "官网素材对比",
      duration: "5秒",
      outputName: "P0-002B-CompareCard-官网素材对比.mov",
      eyebrow: "OFFICIAL SOURCE DIFF",
      title: "外部素材引用对比",
      leftLabel: "ANTHROPIC DOCS",
      leftText: "官方文档|可自动截图|需记录 URL",
      rightLabel: "CURSOR DOCS",
      rightText: "官方文档|可自动截图|适合做证据卡",
      verdict: "能自动抓的素材，也必须进入 manifest 做来源和置信度记录。",
      componentProps: {
        leftImagePath: "opc-showcase/assets/external/anthropic-claude-code.png",
        rightImagePath: "opc-showcase/assets/external/cursor-docs.png",
      },
    }),
  },
  {
    section: "P0 EVIDENCE",
    subtitle: "这是抓取失败样本：OpenAI 官方页面触发 Cloudflare，需要进入 action_required。",
    effect: fx({
      mode: "自动",
      id: "P0-001C",
      type: "EvidenceCard",
      anchor: "文件名是索引，Brief 是导演，视觉识别是质检员。",
      name: "抓取失败边界",
      duration: "5秒",
      outputName: "P0-001C-EvidenceCard-抓取失败边界.mov",
      sourceLabel: "SOURCE_BLOCKED",
      sourceType: "official_website_blocked",
      sourceUrl: "https://platform.openai.com/docs/overview",
      image: "opc-showcase/assets/external/openai-docs-overview.png",
      title: "OpenAI 官方页被风控拦截",
      takeaway: "自动抓取失败时，不伪造证据，改写 action_required 让用户补素材或换来源。",
      confidence: 0.18,
      status: "warning",
    }),
  },
  {
    section: "P0 METRIC",
    subtitle: "MetricCounterCard 用一个数字强调浪费比例或效率变化。",
    effect: fx({
      mode: "自动",
      id: "P0-003",
      type: "MetricCounterCard",
      anchor: "你用 AI 生成的 90% 内容，最后都会变成垃圾。",
      name: "浪费比例",
      duration: "4秒",
      outputName: "P0-003-MetricCounterCard-浪费比例.mov",
      eyebrow: "WASTE SCAN",
      title: "AI 内容浪费率",
      startValue: 0,
      endValue: 90,
      suffix: "%",
      status: "danger",
      conclusion: "不能找回、不能复用、不能迭代，就会变成一次性消耗品。",
    }),
  },
  {
    section: "P0 FLOW",
    subtitle: "FlowPipelineCard 让 OPC 闭环变成可视化流程。",
    effect: fx({
      mode: "自动",
      id: "P0-004",
      type: "FlowPipelineCard",
      anchor: "背后更重要的是：选题是怎么来的？",
      name: "OPC 内容闭环",
      duration: "5秒",
      outputName: "P0-004-FlowPipelineCard-OPC内容闭环.mov",
      eyebrow: "CONTENT PIPELINE",
      title: "内容资产闭环",
      steps: ["母题库", "文章资产", "视频脚本", "封面素材", "发布", "数据回流"],
      highlightStep: 5,
      takeaway: "闭环的关键，是数据能回到下一次选题和脚本。",
    }),
  },
  {
    section: "P0 TERMINAL",
    subtitle: "TerminalLogCard 用系统日志表达自动化过程。",
    effect: fx({
      mode: "自动",
      id: "P0-005",
      type: "TerminalLogCard",
      anchor: "我现在越来越强烈地感受到一件事。",
      name: "资产入库日志",
      duration: "4秒",
      outputName: "P0-005-TerminalLogCard-资产入库日志.mov",
      eyebrow: "ASSET INGEST",
      logs: [
        { time: "00:01", level: "info", text: "scan article source..." },
        { time: "00:04", level: "info", text: "build visual brief..." },
        { time: "00:07", level: "warning", text: "private screenshots require blur..." },
        { time: "00:10", level: "success", text: "render preview ready." },
      ],
    }),
  },
  {
    section: "P0 QUOTE",
    subtitle: "QuoteCard 用于开头、转折或结尾的核心判断。",
    effect: fx({
      mode: "自动",
      id: "P0-006",
      type: "QuoteCard",
      anchor: "内容，不等于内容资产。",
      name: "核心金句",
      duration: "4秒",
      outputName: "P0-006-QuoteCard-核心金句.mov",
      quote: "内容，不等于内容资产",
      authorLabel: "C哥OPC / SYSTEM CONCLUSION",
      tone: "sharp",
    }),
  },
  {
    section: "P1 COST",
    subtitle: "CostCard 把隐藏成本讲清楚：真正贵的是混乱和返工。",
    effect: fx({
      mode: "自动",
      id: "P1-001",
      type: "CostCard",
      anchor: "你每天都在生成，但每天都在丢。",
      name: "混乱成本",
      duration: "4秒",
      outputName: "P1-001-CostCard-混乱成本.mov",
      title: "每月隐形返工成本",
      amountStart: 0,
      amountEnd: 3000,
      currency: "CNY",
      period: "monthly",
      riskLevel: "medium",
      takeaway: "工具不一定贵，真正贵的是每次都从零开始。",
    }),
  },
  {
    section: "P1 BAR",
    subtitle: "BarChartPanel 展示不同内容容器的沉淀程度。",
    effect: fx({
      mode: "自动",
      id: "P1-002",
      type: "BarChartPanel",
      anchor: "这些东西散在哪里？",
      name: "散落位置对比",
      duration: "4秒",
      outputName: "P1-002-BarChartPanel-散落位置对比.mov",
      title: "内容散落位置",
      chartData: [
        { name: "聊天记录", value: 82 },
        { name: "桌面文件", value: 74 },
        { name: "备忘录", value: 55 },
        { name: "资产库", value: 18 },
      ],
      takeaway: "越靠临时容器，越难复用。",
    }),
  },
  {
    section: "P1 LINE",
    subtitle: "LineChartPanel 表达资产积累和一次性产出的长期差距。",
    effect: fx({
      mode: "自动",
      id: "P1-003",
      type: "LineChartPanel",
      anchor: "一个是消耗。一个是积累。",
      name: "资产复利趋势",
      duration: "4秒",
      outputName: "P1-003-LineChartPanel-资产复利趋势.mov",
      title: "内容资产复利",
      chartData: [
        { name: "第1周", value: 8 },
        { name: "第2周", value: 16 },
        { name: "第3周", value: 31 },
        { name: "第4周", value: 58 },
        { name: "第5周", value: 91 },
      ],
      takeaway: "资产库越早建立，后面的每条内容越省力。",
    }),
  },
  {
    section: "P1 DONUT",
    subtitle: "DonutChartPanel 展示一个视频背后的资产结构。",
    effect: fx({
      mode: "自动",
      id: "P1-004",
      type: "DonutChartPanel",
      anchor: "一条视频不只是一条视频。",
      name: "资产结构",
      duration: "4秒",
      outputName: "P1-004-DonutChartPanel-资产结构.mov",
      title: "单条视频资产结构",
      chartData: [
        { name: "选题", value: 22 },
        { name: "文章", value: 28 },
        { name: "脚本", value: 24 },
        { name: "封面", value: 14 },
        { name: "复盘", value: 12 },
      ],
      takeaway: "视频只是前台结果，后台资产才会复用。",
    }),
  },
  {
    section: "P1 GAUGE",
    subtitle: "ProgressGauge 表示自动化覆盖率和风险等级。",
    effect: fx({
      mode: "自动",
      id: "P1-005",
      type: "ProgressGauge",
      anchor: "你的内容管理能力，根本跟不上你的内容生产速度。",
      name: "自动化覆盖率",
      duration: "4秒",
      outputName: "P1-005-ProgressGauge-自动化覆盖率.mov",
      title: "资产化流程覆盖率",
      value: "68",
      status: "warning",
      takeaway: "没有覆盖的环节，就是下一次内容丢失的入口。",
    }),
  },
  {
    section: "P1 AGENT",
    subtitle: "AgentStatusPanel 展示多个工作流节点的执行状态。",
    effect: fx({
      mode: "自动",
      id: "P1-006",
      type: "AgentStatusPanel",
      anchor: "他下一次用 AI，不是从零开始，而是从资产库开始。",
      name: "Agent 状态",
      duration: "4秒",
      outputName: "P1-006-AgentStatusPanel-Agent状态.mov",
      title: "内容系统 Agent",
      nodes: ["选题 Agent", "文章 Agent", "脚本 Agent", "素材 Agent", "渲染 Agent", "复盘 Agent"],
    }),
  },
  {
    section: "P2 NETWORK",
    subtitle: "NetworkGraph 把内容资产库表现成节点网络。",
    effect: fx({
      mode: "自动",
      id: "P2-002",
      type: "NetworkGraph",
      anchor: "它会变成一个选题案例、一个脚本模板、一个封面测试样本。",
      name: "资产网络",
      duration: "4秒",
      outputName: "P2-002-NetworkGraph-资产网络.mov",
      title: "OPC 资产网络",
      nodes: ["母题", "文章", "脚本", "封面", "素材", "发布", "数据", "复盘"],
      takeaway: "资产之间能互相连接，系统才会越用越快。",
    }),
  },
  {
    section: "LEGACY",
    subtitle: "RiskPackage 保留为风险、隐私和低置信度素材提示。",
    effect: fx({
      mode: "自动",
      id: "LEG-001",
      type: "RiskPackage",
      anchor: "找不回来的内容，不是资产。",
      name: "低置信度素材风险",
      duration: "4秒",
      outputName: "LEG-001-RiskPackage-低置信度素材风险.mov",
      eyebrow: "VALIDATION RISK",
      mainTitle: "低置信度素材",
      subtitle: "不能直接进入最终视频",
      riskItems: ["来源不明", "不能支撑观点", "可能含隐私"],
    }),
  },
  {
    section: "LEGACY",
    subtitle: "InfraNetwork 展示系统基础设施关系。",
    effect: fx({
      mode: "自动",
      id: "LEG-002",
      type: "InfraNetwork",
      anchor: "一个是手艺活。一个是系统。",
      name: "内容基础设施",
      duration: "4秒",
      outputName: "LEG-002-InfraNetwork-内容基础设施.mov",
      eyebrow: "CONTENT INFRA",
      mainTitle: "内容基础设施",
      nodes: ["选题库", "文章库", "脚本库", "素材库", "数据复盘"],
      highlightNode: 4,
    }),
  },
  {
    section: "LEGACY",
    subtitle: "MilestoneNumber 展示可积累的资产数量。",
    effect: fx({
      mode: "自动",
      id: "LEG-003",
      type: "MilestoneNumber",
      anchor: "你可以先统一放进一个地方。",
      name: "资产数量",
      duration: "4秒",
      outputName: "LEG-003-MilestoneNumber-资产数量.mov",
      mainNumber: "126",
      suffix: "+",
      mainLabelEn: "CONTENT ASSETS",
      mainLabelZh: "可复用内容资产",
      secondaryNumber: "5",
      secondaryLabelZh: "核心资产库",
    }),
  },
  {
    section: "LEGACY",
    subtitle: "RevenueSignal 表达内容资产最终可以连接商业信号。",
    effect: fx({
      mode: "自动",
      id: "LEG-004",
      type: "RevenueSignal",
      anchor: "能变现的内容，才叫内容资产。",
      name: "商业信号",
      duration: "4秒",
      outputName: "LEG-004-RevenueSignal-商业信号.mov",
      value: "4",
      suffix: "条",
      title: "可变现路径",
      subtitle: "文章 / 视频 / 模板 / 咨询",
      eyebrow: "REVENUE SIGNAL",
    }),
  },
  {
    section: "LEGACY",
    subtitle: "NextEpisodePackage 收束到评论关键词。",
    effect: fx({
      mode: "自动",
      id: "LEG-005",
      type: "NextEpisodePackage",
      anchor: "评论区打资产。",
      name: "下期预告",
      duration: "4秒",
      outputName: "LEG-005-NextEpisodePackage-下期预告.mov",
      eyebrow: "NEXT EPISODE",
      mainTitle: "最小内容资产库",
      subtitle: "普通人也能从一个文件夹开始",
      commentKeyword: "资产",
    }),
  },
  {
    section: "LEGACY",
    subtitle: "AtmosphereOverlay 用作贯穿全片的轻量扫描氛围层。",
    effect: fx({
      mode: "自动",
      id: "LEG-006",
      type: "AtmosphereOverlay",
      anchor: "让每条 OPC 视频像正在运行的 AI 分析系统。",
      name: "系统氛围层",
      duration: "4秒",
      outputName: "LEG-006-AtmosphereOverlay-系统氛围层.mov",
      overlayType: "scanline",
      intensity: "medium",
    }),
  },
];
